# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autoscaler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'autoscaler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61utoscaler.proto\"\x07\n\x05\x45mpty\"#\n\x0eMetricsRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\":\n\x0fMetricsResponse\x12\x11\n\tcpu_usage\x18\x02 \x01(\x01\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x01\"9\n\x0cScaleRequest\x12\x17\n\x0f\x64\x65ployment_name\x18\x01 \x01(\t\x12\x10\n\x08replicas\x18\x02 \x01(\x05\"\x1f\n\rScaleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2i\n\nAutoScaler\x12/\n\nGetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponse\x12*\n\tScalePods\x12\r.ScaleRequest\x1a\x0e.ScaleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autoscaler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_METRICSREQUEST']._serialized_start=29
  _globals['_METRICSREQUEST']._serialized_end=64
  _globals['_METRICSRESPONSE']._serialized_start=66
  _globals['_METRICSRESPONSE']._serialized_end=124
  _globals['_SCALEREQUEST']._serialized_start=126
  _globals['_SCALEREQUEST']._serialized_end=183
  _globals['_SCALERESPONSE']._serialized_start=185
  _globals['_SCALERESPONSE']._serialized_end=216
  _globals['_AUTOSCALER']._serialized_start=218
  _globals['_AUTOSCALER']._serialized_end=323
# @@protoc_insertion_point(module_scope)
